# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.java.home=C:/Program Files/Eclipse Adoptium/jdk-25.0.2.10-hotspot

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1
loader_version=0.19.3

# Mod Properties
mod_version=1.1.5
maven_group=qualet
archives_base_name=irlite-cml

# Dependencies
fabric_version=0.145.1+26.1
irl_core_version=1.1.5
